# Generated by Django 3.2.16 on 2023-01-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('roll_number', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80, null=True)),
                ('mobile', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
